import "@repo/ui/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppBar } from "./components/navigation/navbar/navbar";
import Providers from "./providers/Provider";
import { Toaster } from "@repo/ui/components/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Docs",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div id="portal" />
          <AppBar />
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
